print("casa das primas ") 
print(" Regras:")
print(" nao ser gay")


print(" ser maior de idade")

nome = input("qual seu nome parceiro?  ")

idade = int(input("tem quantos anos comedia? "))

if idade >= 18:
    print("entra ae"  + nome + " bem vindo ao melhor puteiro do brasil. escolhe a melhor puta  " )
else:
    print("você é menor de idade, vaza virjola")
    
    print("𓀐𓂺 𓀐𓂸")
    print("🍆🍑😩👉👌💦")
  